# Generated by Django 4.1.1 on 2022-10-11 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta',
            name='data_inicio',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 11, 23, 13, 54, 752935)),
        ),
    ]
