# Generated by Django 4.1.1 on 2022-09-06 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igredientes', models.TextField()),
                ('data_comeco', models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 6, 23, 26, 44, 464232))),
            ],
        ),
    ]
