# Generated by Django 4.1.1 on 2022-09-23 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dieta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(
                        verbose_name=datetime.datetime(2022, 9, 23, 13, 58, 6, 656923)
                    ),
                ),
                ("data_final", models.DateTimeField()),
                ("dieta_concluida", models.BooleanField(default=False)),
                ("descricao", models.TextField()),
                (
                    "dias_semana",
                    models.CharField(
                        choices=[
                            ("Seg", "Segunda-Feira"),
                            ("Ter", "Terça-Feira"),
                            ("Qua", "Quarta-Feira"),
                            ("Qui", "Quinta-Feira"),
                            ("Sex", "Sexta-feira"),
                            ("Sab", "Sabado"),
                            ("Dom", "Domingo"),
                        ],
                        default="Seg",
                        max_length=3,
                    ),
                ),
                ("ingredientes", models.TextField()),
            ],
            options={
                "verbose_name": "Dietas",
            },
        ),
    ]
