# Generated by Django 4.1.1 on 2022-09-06 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='dieta_publica',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='data_comeco',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 6, 23, 31, 9, 353066)),
        ),
    ]
