# Generated by Django 4.1.1 on 2022-09-23 17:04

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("dietas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dieta",
            options={"verbose_name": "Dieta"},
        ),
        migrations.AlterField(
            model_name="dieta",
            name="data_inicio",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2022, 9, 23, 14, 4, 24, 429546)
            ),
        ),
        migrations.AlterField(
            model_name="dieta",
            name="dias_semana",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Seg", "Segunda-Feira"),
                    ("Ter", "Terça-Feira"),
                    ("Qua", "Quarta-Feira"),
                    ("Qui", "Quinta-Feira"),
                    ("Sex", "Sexta-feira"),
                    ("Sab", "Sabado"),
                    ("Dom", "Domingo"),
                ],
                default="Seg",
                max_length=3,
            ),
        ),
    ]
